### PR TITLE
Split project packages

### LINKED ISSUE #155: split-project-packages
I see a draft branch, so logging as an issue. https://github.com/open-contracting/ocdskit/tree/split-project-packages

### PR DESCRIPTION
**Pull request by duncandewhurst**
Closes #155

### CODE REVIEW

**Comment by duncandewhurst** [comment]
@jpmckinney how do I run the tests locally?

I'm not sure why the test is failing as `tests/fixtures/oc4ids/project_package_split.json` is the same as the first file generated by `cat tests/fixtures/oc4ids/project_package.json | ocdskit split-project-packages 1 | split -l 1 -a 4`

**Comment by jpmckinney** [comment]
To run the tests:

```
pip install .[test]
pytest
```

**Comment by jpmckinney** [comment]
The expected output needs to include the full output. I generated the file with:

```
cat tests/fixtures/oc4ids/project_package.json | ocdskit split-project-packages 1 > tests/fixtures/oc4ids/project_package_split.json
```

**Comment by jpmckinney** [comment]
I added a note here about how to test packages: https://ocp-software-handbook.readthedocs.io/en/latest/python/packages.html#automated-testing

Also linked from https://ocp-software-handbook.readthedocs.io/en/latest/python/quality.html

**Comment by jpmckinney** [comment]
If you add a `packages` key to `project_package.json`, we can increase test coverage.

**Comment by jpmckinney** [comment]
> If you add a `packages` key to `project_package.json`, we can increase test coverage.

Nevermind – I can just delete that code, since project packages don't have a `packages` field.

**Pull request merged**
