### PR TITLE
Replace deepcopy with more specific copys, to keep __reference__

### LINKED ISSUE #42: mapping-sheet: script omits original description when a reference is used for an object
Currently the flattened schema produced by the mapping-sheet script omits the original description (and other properties) for objects where a reference is used, this means users of the flattened schema may miss out on important context.

**Example 1:**

The `description` for `buyer` is:

> The buyer is the entity whose budget will be used to purchase the goods. This may be different from the procuring entity who may be specified in the tender data.

However in the flattened schema this is replaced by the `description` from the referenced `organizationReference` object:

path | title | description
-- | -- | --
buyer | Organization reference | The id and name of the party being referenced. Used to cross-reference to the parties section

So the user misses out on the distinction between buyer and procuring entity.

**Example 2:**

The `description` for `organizationReference/address` is:

> (Deprecated outside the parties section)

However in the flattened schema this is replaced by the `description` from the referenced `address` object:

path | title | description
-- | -- | --
buyer/address | Address | An address. This may be the legally registered address of the organization, or may be a correspondence address for this particular contracting process.

So the user can't see that the `address` object is deprecated in this case (the deprecation properties are not set because the `address` object itself has not been deprecated, just it's use in this location)

**Suggested approach:**

Where the reference is inside an array the mapping-sheet already produces two rows, one for the array and one for the objects in it, e.g.

path | title | description | type
-- | -- | -- | --
planning/documents | Documents | A list of documents related to the planning process. | array
planning/documents | Document | Links to, or descriptions of, external documents can be attached at various locations within the standard. Documents may be supporting information, formal notices, downloadable forms, or any other kind of resource that should be made public as part of full open contracting. | object

We could extend that behavior to references which aren't in arrays, using a type of "reference" for the row displaying the properties of the parent:

path | title | description | type
-- | -- | -- | --
buyer | Buyer | The buyer is the entity whose budget will be used to purchase the goods. This may be different from the procuring entity who may be specified in the tender data. | reference
buyer | Organization reference | The id and name of the party being referenced. Used to cross-reference to the parties section | object

### PR DESCRIPTION
**Pull request by Bjwebb**
Closes #42

### CODE REVIEW

**Comment by duncandewhurst** [comment]
@Bjwebb the behaviour now seems to be that the description from the reference is used in the flattened schema, rather than the description of the object being referred to.

I think that's an improvement on the existing behaviour, but it would be preferable to have a row for both the description from the reference and the description from the object being referred to, since sometimes important information is split across both, e.g. for `budget`, `organizationReference` and `classification`. Would it be a lot of work to add that functionality? (I described it in more detail in #42)

**Comment by Bjwebb** [comment]
@duncandewhurst Ah sorry, I'd missed that. I've added that functionality. I have mixed feelings about using `reference` for the type though, as its not the type that should be in the actual JSON file, so I worry it may cause confusion.

**Comment by duncandewhurst** [comment]
thanks @Bjwebb, good point on the use of `reference`, the other options would be:

1. Use `object` as the type, so there would be two rows with the only difference being the description
2. Concatenate the descriptions from the reference and the object being referred to into a single row

Neither of which seem ideal, unless there's anything else you can think of?

**Comment by jpmckinney** [comment]
@duncandewhurst Please feel free to merge if the new output is what you expect/want.

**Comment by jpmckinney** [comment]
I assume the new output is fine.

**Pull request merged**
